// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github-bot/ent/pulls"
	"github-bot/ent/schema"
	"github-bot/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pullsFields := schema.Pulls{}.Fields()
	_ = pullsFields
	// pullsDescPrID is the schema descriptor for prID field.
	pullsDescPrID := pullsFields[1].Descriptor()
	// pulls.DefaultPrID holds the default value on creation for the prID field.
	pulls.DefaultPrID = pullsDescPrID.Default.(int64)
	// pullsDescRepoID is the schema descriptor for repoID field.
	pullsDescRepoID := pullsFields[3].Descriptor()
	// pulls.DefaultRepoID holds the default value on creation for the repoID field.
	pulls.DefaultRepoID = pullsDescRepoID.Default.(int64)
	// pullsDescComment is the schema descriptor for comment field.
	pullsDescComment := pullsFields[5].Descriptor()
	// pulls.DefaultComment holds the default value on creation for the comment field.
	pulls.DefaultComment = pullsDescComment.Default.(int64)
	// pullsDescCheckRunID is the schema descriptor for checkRunID field.
	pullsDescCheckRunID := pullsFields[8].Descriptor()
	// pulls.DefaultCheckRunID holds the default value on creation for the checkRunID field.
	pulls.DefaultCheckRunID = pullsDescCheckRunID.Default.(int64)
	// pullsDescCheckRunResult is the schema descriptor for checkRunResult field.
	pullsDescCheckRunResult := pullsFields[9].Descriptor()
	// pulls.DefaultCheckRunResult holds the default value on creation for the checkRunResult field.
	pulls.DefaultCheckRunResult = pullsDescCheckRunResult.Default.(string)
	// pullsDescHeadSha is the schema descriptor for headSha field.
	pullsDescHeadSha := pullsFields[10].Descriptor()
	// pulls.DefaultHeadSha holds the default value on creation for the headSha field.
	pulls.DefaultHeadSha = pullsDescHeadSha.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescGithubID is the schema descriptor for github_id field.
	userDescGithubID := userFields[0].Descriptor()
	// user.GithubIDValidator is a validator for the "github_id" field. It is called by the builders before save.
	user.GithubIDValidator = userDescGithubID.Validators[0].(func(int64) error)
	// userDescBangumiID is the schema descriptor for bangumi_id field.
	userDescBangumiID := userFields[1].Descriptor()
	// user.BangumiIDValidator is a validator for the "bangumi_id" field. It is called by the builders before save.
	user.BangumiIDValidator = userDescBangumiID.Validators[0].(func(int64) error)
}
