// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github-bot/ent/schema"
	"github-bot/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescGithubID is the schema descriptor for github_id field.
	userDescGithubID := userFields[0].Descriptor()
	// user.GithubIDValidator is a validator for the "github_id" field. It is called by the builders before save.
	user.GithubIDValidator = userDescGithubID.Validators[0].(func(int64) error)
	// userDescBangumiID is the schema descriptor for bangumi_id field.
	userDescBangumiID := userFields[1].Descriptor()
	// user.BangumiIDValidator is a validator for the "bangumi_id" field. It is called by the builders before save.
	user.BangumiIDValidator = userDescBangumiID.Validators[0].(func(int64) error)
}
