// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github-bot/ent/predicate"
	"github-bot/ent/pulls"
	"github-bot/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetGithubID sets the "github_id" field.
func (uu *UserUpdate) SetGithubID(i int64) *UserUpdate {
	uu.mutation.ResetGithubID()
	uu.mutation.SetGithubID(i)
	return uu
}

// AddGithubID adds i to the "github_id" field.
func (uu *UserUpdate) AddGithubID(i int64) *UserUpdate {
	uu.mutation.AddGithubID(i)
	return uu
}

// SetBangumiID sets the "bangumi_id" field.
func (uu *UserUpdate) SetBangumiID(i int64) *UserUpdate {
	uu.mutation.ResetBangumiID()
	uu.mutation.SetBangumiID(i)
	return uu
}

// SetNillableBangumiID sets the "bangumi_id" field if the given value is not nil.
func (uu *UserUpdate) SetNillableBangumiID(i *int64) *UserUpdate {
	if i != nil {
		uu.SetBangumiID(*i)
	}
	return uu
}

// AddBangumiID adds i to the "bangumi_id" field.
func (uu *UserUpdate) AddBangumiID(i int64) *UserUpdate {
	uu.mutation.AddBangumiID(i)
	return uu
}

// ClearBangumiID clears the value of the "bangumi_id" field.
func (uu *UserUpdate) ClearBangumiID() *UserUpdate {
	uu.mutation.ClearBangumiID()
	return uu
}

// AddPullRequestIDs adds the "pull_requests" edge to the Pulls entity by IDs.
func (uu *UserUpdate) AddPullRequestIDs(ids ...int) *UserUpdate {
	uu.mutation.AddPullRequestIDs(ids...)
	return uu
}

// AddPullRequests adds the "pull_requests" edges to the Pulls entity.
func (uu *UserUpdate) AddPullRequests(p ...*Pulls) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.AddPullRequestIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearPullRequests clears all "pull_requests" edges to the Pulls entity.
func (uu *UserUpdate) ClearPullRequests() *UserUpdate {
	uu.mutation.ClearPullRequests()
	return uu
}

// RemovePullRequestIDs removes the "pull_requests" edge to Pulls entities by IDs.
func (uu *UserUpdate) RemovePullRequestIDs(ids ...int) *UserUpdate {
	uu.mutation.RemovePullRequestIDs(ids...)
	return uu
}

// RemovePullRequests removes "pull_requests" edges to Pulls entities.
func (uu *UserUpdate) RemovePullRequests(p ...*Pulls) *UserUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uu.RemovePullRequestIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, UserMutation](ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UserUpdate) check() error {
	if v, ok := uu.mutation.GithubID(); ok {
		if err := user.GithubIDValidator(v); err != nil {
			return &ValidationError{Name: "github_id", err: fmt.Errorf(`ent: validator failed for field "User.github_id": %w`, err)}
		}
	}
	if v, ok := uu.mutation.BangumiID(); ok {
		if err := user.BangumiIDValidator(v); err != nil {
			return &ValidationError{Name: "bangumi_id", err: fmt.Errorf(`ent: validator failed for field "User.bangumi_id": %w`, err)}
		}
	}
	return nil
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.GithubID(); ok {
		_spec.SetField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.AddedGithubID(); ok {
		_spec.AddField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.BangumiID(); ok {
		_spec.SetField(user.FieldBangumiID, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.AddedBangumiID(); ok {
		_spec.AddField(user.FieldBangumiID, field.TypeInt64, value)
	}
	if uu.mutation.BangumiIDCleared() {
		_spec.ClearField(user.FieldBangumiID, field.TypeInt64)
	}
	if uu.mutation.PullRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PullRequestsTable,
			Columns: []string{user.PullRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pulls.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedPullRequestsIDs(); len(nodes) > 0 && !uu.mutation.PullRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PullRequestsTable,
			Columns: []string{user.PullRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pulls.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.PullRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PullRequestsTable,
			Columns: []string{user.PullRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pulls.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetGithubID sets the "github_id" field.
func (uuo *UserUpdateOne) SetGithubID(i int64) *UserUpdateOne {
	uuo.mutation.ResetGithubID()
	uuo.mutation.SetGithubID(i)
	return uuo
}

// AddGithubID adds i to the "github_id" field.
func (uuo *UserUpdateOne) AddGithubID(i int64) *UserUpdateOne {
	uuo.mutation.AddGithubID(i)
	return uuo
}

// SetBangumiID sets the "bangumi_id" field.
func (uuo *UserUpdateOne) SetBangumiID(i int64) *UserUpdateOne {
	uuo.mutation.ResetBangumiID()
	uuo.mutation.SetBangumiID(i)
	return uuo
}

// SetNillableBangumiID sets the "bangumi_id" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableBangumiID(i *int64) *UserUpdateOne {
	if i != nil {
		uuo.SetBangumiID(*i)
	}
	return uuo
}

// AddBangumiID adds i to the "bangumi_id" field.
func (uuo *UserUpdateOne) AddBangumiID(i int64) *UserUpdateOne {
	uuo.mutation.AddBangumiID(i)
	return uuo
}

// ClearBangumiID clears the value of the "bangumi_id" field.
func (uuo *UserUpdateOne) ClearBangumiID() *UserUpdateOne {
	uuo.mutation.ClearBangumiID()
	return uuo
}

// AddPullRequestIDs adds the "pull_requests" edge to the Pulls entity by IDs.
func (uuo *UserUpdateOne) AddPullRequestIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddPullRequestIDs(ids...)
	return uuo
}

// AddPullRequests adds the "pull_requests" edges to the Pulls entity.
func (uuo *UserUpdateOne) AddPullRequests(p ...*Pulls) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.AddPullRequestIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearPullRequests clears all "pull_requests" edges to the Pulls entity.
func (uuo *UserUpdateOne) ClearPullRequests() *UserUpdateOne {
	uuo.mutation.ClearPullRequests()
	return uuo
}

// RemovePullRequestIDs removes the "pull_requests" edge to Pulls entities by IDs.
func (uuo *UserUpdateOne) RemovePullRequestIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemovePullRequestIDs(ids...)
	return uuo
}

// RemovePullRequests removes "pull_requests" edges to Pulls entities.
func (uuo *UserUpdateOne) RemovePullRequests(p ...*Pulls) *UserUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uuo.RemovePullRequestIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks[*User, UserMutation](ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UserUpdateOne) check() error {
	if v, ok := uuo.mutation.GithubID(); ok {
		if err := user.GithubIDValidator(v); err != nil {
			return &ValidationError{Name: "github_id", err: fmt.Errorf(`ent: validator failed for field "User.github_id": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.BangumiID(); ok {
		if err := user.BangumiIDValidator(v); err != nil {
			return &ValidationError{Name: "bangumi_id", err: fmt.Errorf(`ent: validator failed for field "User.bangumi_id": %w`, err)}
		}
	}
	return nil
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.GithubID(); ok {
		_spec.SetField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.AddedGithubID(); ok {
		_spec.AddField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.BangumiID(); ok {
		_spec.SetField(user.FieldBangumiID, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.AddedBangumiID(); ok {
		_spec.AddField(user.FieldBangumiID, field.TypeInt64, value)
	}
	if uuo.mutation.BangumiIDCleared() {
		_spec.ClearField(user.FieldBangumiID, field.TypeInt64)
	}
	if uuo.mutation.PullRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PullRequestsTable,
			Columns: []string{user.PullRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pulls.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedPullRequestsIDs(); len(nodes) > 0 && !uuo.mutation.PullRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PullRequestsTable,
			Columns: []string{user.PullRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pulls.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.PullRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PullRequestsTable,
			Columns: []string{user.PullRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pulls.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
