// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Pulls is the predicate function for pulls builders.
type Pulls func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
